embedding_model:
  dim: 768
  dtype: float32
  embedding_cache_name: vec-cache
  model: sentence-transformers/all-mpnet-base-v2
  type: hf
index_name: cars
queries: "../resources/cars/car_queries.json"
qrels: "../resources/cars/car_qrels.json"
ret_k: 6
search_methods:
- base_vector
- pre_filter_vector
study_id: test-search-study
